pages/urls.py
# pages/urls.py

from django.urls import path
from pages import views

urlpatterns = [
    path("", views.home, name='home'),
    path("open_cv/", views.open_cv, name='resume'),
]

portfolio/urls.py
# personal_portfolio/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
    path("projects/", include("projects.urls", namespace='projects')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/urls.py
# projects/urls.py

from django.urls import path
from projects import views

app_name='projects'

urlpatterns = [
    path("", views.contact_form, name="contact_form"),
    path("<str:title>/", views.project_detail, name="project_detail"),
]

pages/models.py
from django.db import models

# Create your models here.

projects/models.py
# projects/models.py
from django.db import models
from django.urls import reverse


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    image = models.FileField(upload_to="project_images/", blank=True)
    url = models.URLField(max_length=2083)

    class Meta:
        ordering = ['title']
        indexes = [
            models.Index(fields=['title',]),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('projects:project_detail', args=[self.title])

pages/views.py
# pages/views.py

import os

from django.conf import settings
from django.http import FileResponse

from django.shortcuts import render
from projects.models import Project

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage, InvalidPage


def home(request):
    project_list = Project.objects.all()
    paginator = Paginator(project_list, 3)
    page_number = request.GET.get('page', 1)

    try:
        projects = paginator.page(page_number)
    except (EmptyPage):
        projects = paginator.page(page_number)
    except (InvalidPage):
        projects = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        projects = paginator.page(1)
    return render(request, "pages/home.html", {'projects': projects})


def open_cv(request):
    cv_path = os.path.join(settings.MEDIA_ROOT, 'cv/Django.pdf')
    return FileResponse(open(cv_path, 'rb'), content_type='application/pdf')

projects/views.py
# projects/views.py

from django.http import JsonResponse
from projects.models import Project
from django.shortcuts import render, get_object_or_404, redirect

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage, InvalidPage
from django.core.mail import send_mail


def project_index(request):
    project_list = Project.objects.all()
    paginator = Paginator(project_list, 2)
    page_number = request.GET.get('page', 1)

    try:
        projects = paginator.page(page_number)
    except (EmptyPage):
        projects = paginator.page(page_number)
    except (InvalidPage):
        projects = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        projects = paginator.page(1)

    return render(request, "projects/project_index.html", {
        "projects": projects
    })


def project_detail(request, title):
    project = get_object_or_404(Project, title=title)
    return render(request, "projects/project_detail.html", {
        "project": project
    })


def contact_form(request):
    if request.method == 'POST':
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        email = request.POST.get('email')

        # Code to send email goes here
        send_mail(subject=subject, message=message, from_email=email, recipient_list=[
                  'juliusn411@gmail.com', 'njeruthelearner@gmail.com'])

        return redirect('home')
    else:
        return JsonResponse({'status': 'error'}, status=400)

pages/templates/pages/home.html
{% extends "base.html" %}
<!-- pages/templates/pages/home.html -->

{% load static %} {% block page_content %}
<!-- Contact icons -->
{% include "icons.html" %}

<!-- Navigation bar -->
{% include "header.html" %}
<main class="mx-auto max-w-4xl">
  <!-- Introduction -->
  {% include "introduction.html" %}

  <hr class="mx-auto w-1/2 bg-black dark:bg-white" />

  <!-- About me -->
  {% include "about.html" %}

  <hr class="mx-auto w-1/2 bg-black dark:bg-white" />

  <!-- Projects -->
  {% include "projects.html" %}

  <hr class="mx-auto w-1/2 bg-black dark:bg-white" />

  <!-- Testimonials -->
  {% include "testimonials.html" %}

  <hr class="mx-auto w-1/2 bg-black dark:bg-white" />

  <!-- Contact -->
  {% include "contact-me.html" %}
</main>

{% include "footer.html" %} {% endblock page_content %}

projects/templates/includes/pagination.html
<div class="flex justify-center gap-8">
  <span class="step-links">
    {% if page.has_previous %}
    <a
      class="text-slate-900 dark:text-white"
      href="?page={{ page.previous_page_number }}#projects"
      >Previous</a
    >
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
    <a
      class="text-slate-900 dark:text-white"
      href="?page={{ page.next_page_number }}#projects"
      >Next</a
    >
    <!-- <button
      type="submit"
      class="p-3 rounded-xl border border-solid border-slate-900 bg-teal-700 text-white hover:bg-teal-600 active:bg-teal-500 dark:border-none"
    >
      <a
        class="text-slate-900 dark:text-white"
        href="?page={{ page.next_page_number }}#projects"
        >Next</a
      >
    </button> -->
    {% endif %}
  </span>
</div>
<!-- https://www.linkedin.com/in/julius-njeru-37158924b/ -->

projects/templates/projects/project_detail.html
{% extends "base.html" %}
<!-- projects/templates/projects/project_detail.html -->

{% block title %} {{ project.title }} | Project details {% endblock title %}

<!--  -->
{% block page_content %}

<section
  class="widescreen:section-min-height tallscreen:section-min-height my-12 scroll-mt-20 p-6"
>
  <div class="mx-auto text-left text-white">
    <a href="{{ request.META.HTTP_REFERER }}">&lt; Back</a>
  </div>
  <h2
    class="mb-6 text-center text-4xl font-bold text-slate-900 dark:text-white sm:text-5xl"
  >
    {{ project.title }}
  </h2>
  <hr />
  <section
    class="widescreen:section-min-height tallscreen:section-min-height mb-12 flex flex-col-reverse items-center justify-center gap-8 p-6 sm:flex-row"
  >
    <article class="sm:w-1/2">
      <h5>About the project:</h5>
      <p
        class="mt-4 max-w-md text-center text-xl text-slate-700 dark:text-slate-400 sm:text-left"
      >
        {{ project.description }}
      </p>

      <br />
      <span
        ><a target="_blank" href="{{project.url}}"
          ><img
            style="height: 22px; margin-right: 10px"
            src="{% static 'img/github.png' %}"
            alt="" /></a
      ></span>

      <br />
      <hr class="bg-black dark:bg-white" />
      <br />
      <h5 class="pt-4 underline text-xl text-slate-400">Technology used:</h5>
      <p class="text-3xl">{{ project.technology }}</p>
    </article>
    <div class="col-md-8">
      {% if project.image %}
      <img
        alt="{{project.name}} image."
        class="mx-auto w-1/2 rounded"
        src="{{ project.image.url }}"
        width="100%"
      />
      {% endif %}
    </div>
  </section>
</section>

{% endblock page_content %}

templates/about.html
{% load static %}

<section
  id="aboutme"
  class="widescreen:section-min-height tallscreen:section-min-height my-12 scroll-mt-20 p-6"
>
  <h2
    class="mb-6 text-center text-4xl font-bold text-slate-900 dark:text-white sm:text-5xl"
  >
    About me
  </h2>
  <section
    class="widescreen:section-min-height tallscreen:section-min-height mb-12 flex scroll-mt-40 flex-col items-center justify-center gap-8 p-6 sm:flex-row"
    style="align-items: flex-start"
  >
    <article class="sm:w-1/2">
      <p
        class="mt-4 max-w-md text-center text-xl text-slate-700 dark:text-slate-400 sm:text-left"
      >
        I am an entry level software engineer with expertise in Web application
        development. Through continous learning and practice, I have managed to
        reach a strong intermediate level in the following array of
        technologies:
      </p>
      <ul class="text-sm text-center sm:text-left mt-4 text-slate-700">
        <li>Django</li>
        <li>Docker</li>
        <li>JavaScript</li>
        <li>TailwindCSS</li>
        <li>Git & GitHub</li>
        <li>HTML5 & CSS3</li>
        <li>Django Rest framework</li>
      </ul>
    </article>
    <div class="flex flex-col items-center">
      <p
        class="mt-4 max-w-md text-center text-xl text-slate-700 dark:text-slate-400 sm:text-left mt-4"
      >
        I also posses interpersonal skills which are crucial for every software
        development role like:
      </p>
      <ul class="text-sm mt-4 text-slate-700 text-center sm:text-left">
        <li>A keen eye to details.</li>
        <li>Good communication skills.</li>
        <li>Excellent problem solving sills.</li>
        <li>Excellent troubleshooting and debugging skills.</li>
      </ul>
    </div>
  </section>
  <div class="flex items-center justify-center">
    <button
      class="w-48 rounded-xl border border-solid border-slate-900 bg-teal-700 p-3 text-white hover:bg-teal-600 active:bg-teal-500 dark:border-none"
    >
      <a href="{% url 'resume' %}" target="_blank">Check resume</a>
    </button>
  </div>
</section>

templates/base.html
<!-- templates/base.html -->

<!DOCTYPE html>
{% load static %} 
<html lang="en">
  <head>
    <meta charset="utf-8" />

    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <title>{% block title %}My Personal Portfolio{% endblock title %}</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
      rel="stylesheet"
    />
    <!-- <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
    /> -->
  </head>
  <body
    style="
      font-family: Montserrat, system-ui, -apple-system, BlinkMacSystemFont,
        'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans',
        'Helvetica Neue', sans-serif;
    "
    class="min-h-screen bg-slate-50 dark:bg-black dark:text-white relative"
  >
    {% block page_content %}{% endblock page_content %}
    <button
      style="
        position: fixed;
        right: 60px; /* Adjust the left position as needed */
        bottom: 60px; /* Adjust the bottom position as needed */
        z-index: 999;
      "
      id="whatsappButton"
    >
      <img
        style="height: 64px; padding: 0; margin: 0"
        src="{% static 'img/whatsapp.png' %}"
        alt=""
      />
    </button>

    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/copyright.js' %}"></script>
    <script src="{% static 'js/whatsapp.js' %}"></script>
  </body>
</html>

templates/contact-me.html
<section
  id="contact"
  class="widescreen:section-min-height tallscreen:section-min-height my-12 scroll-mt-16 p-6"
>
  <h2
    class="mb-6 text-center text-4xl font-bold text-slate-900 dark:text-white sm:text-5xl"
  >
    Contact me
  </h2>
  <form
    method="post"
    action="{% url 'projects:contact_form' %}"
    class="items-left mx-auto flex max-w-4xl flex-col gap-4 text-2xl sm:text-3xl"
  >
    {% csrf_token %}
    <label for="subject">Subject:</label>
    <input
      type="text"
      id="subject"
      name="subject"
      required
      minlength="3"
      maxlength="60"
      placeholder="Your Subject"
      class="w-full rounded-xl border border-solid border-slate-900 p-3 text-2xl text-black dark:border-none sm:text-3xl"
    />
    <label for="email">Email:</label>
    <input
      type="email"
      id="email"
      name="email"
      required
      minlength="3"
      maxlength="60"
      placeholder="Your email address"
      class="w-full rounded-xl border border-solid border-slate-900 p-3 text-2xl text-black dark:border-none sm:text-3xl"
    />
    <label for="message">Message:</label>
    <textarea
      name="message"
      id="message"
      cols="30"
      rows="10"
      placeholder="Your Message"
      required
      class="w-full rounded-xl border border-solid border-slate-900 p-3 text-2xl text-black dark:border-none sm:text-3xl"
    ></textarea>
    <input
      type="submit"
      class="w-48 rounded-xl border border-solid border-slate-900 bg-teal-700 p-3 text-white hover:bg-teal-600 active:bg-teal-500 dark:border-none"
      value="Reach out"
    />
  </form>
</section>

templates/footer.html
{% load static %}

<footer id="footer" class="bg-teal-700 text-xl text-white">
  <section
    class="mx-auto flex max-w-4xl flex-col p-4 sm:flex-row sm:justify-between"
  >
    <address>
      <h2>Location: Thika, Nairobi</h2>
      <div class="flex justify-between pt-3">
        <span class="bg-teal-700"
          ><a target="_blank" href="https://github.com/njeruthuo"
            ><img
              style="height: 22px; margin-right: 10px"
              src="{% static 'img/github.png' %}"
              alt="" /></a
        ></span>
        <span class="bg-teal-700"
          ><a
            target="_blank"
            href="https://www.linkedin.com/in/julius-njeru-37158924b/"
            ><img
              style="height: 22px; margin-right: 10px"
              src="{% static 'img/linkedin.png' %}"
              alt="" /></a
        ></span>
        <span class="bg-teal-700"
          ><a
            class="bg-teal-700"
            target="_blank"
            href="mailto:juliusn411@gmail.com"
            ><img
              style="height: 22px; margin-right: 10px"
              src="{% static 'img/email.png' %}"
              alt="" /></a
        ></span>
      </div>
    </address>

    <div class="flex flex-col sm:gap-2">
      <p class="text-right">Copyright &copy; <span id="year"></span></p>
      <p class="text-right">All Rights Reserved</p>
    </div>
  </section>
</footer>

templates/header.html
{% load static %}

<header class="sticky top-0 z-10 bg-teal-700 text-white">
  <section class="mx-auto flex max-w-4xl items-center justify-between p-4">
    <h1 class="text-3xl font-medium">
      <a href="#intro">My Portfolio</a>
    </h1>
    <div>
      <button
        id="hamburger-button"
        class="relative h-8 w-8 cursor-pointer text-3xl md:hidden"
      >
        <!-- &#9776; -->
        <div
          class="absolute top-4 -mt-0.5 h-1 w-8 rounded bg-white transition-all duration-500 before:absolute before:h-1 before:w-8 before:-translate-x-4 before:-translate-y-3 before:rounded before:bg-white before:transition-all before:duration-500 before:content-[''] after:absolute after:h-1 after:w-8 after:-translate-x-4 after:translate-y-3 after:rounded after:bg-white after:transition-all after:duration-500 after:content-['']"
        ></div>
      </button>
      <nav class="hidden space-x-8 text-xl md:block" aria-label="main">
        <a href="#aboutme" class="hover:opacity-90">AboutMe</a>
        <a href="#projects" class="hover:opacity-90">Projects</a>
        <a href="#testimonials" class="hover:opacity-90">Testimonials</a>
        <a href="#contact" class="hover:opacity-90">Contact me</a>
      </nav>
    </div>
  </section>
  <section
    id="mobile-menu"
    class="top-68 justify-center absolute hidden w-full origin-top animate-open-menu flex-col bg-black text-5xl"
  >
    <nav
      class="flex min-h-screen flex-col items-center py-8"
      aria-label="mobile"
    >
      <a href="#hero" class="w-full py-6 text-center hover:opacity-90">Home</a>
      <a href="#aboutme" class="w-full py-6 text-center hover:opacity-90"
        >About me</a
      >
      <a href="#projects" class="w-full py-6 text-center hover:opacity-90"
        >Projects</a
      >
      <a href="#testimonials" class="w-full py-6 text-center hover:opacity-90"
        >Testimonials</a
      >
      <a href="#contact" class="w-full py-6 text-center hover:opacity-90"
        >Contact me</a
      >
      <a href="#footer" class="w-full py-6 text-center hover:opacity-90"
        >How to find me</a
      >
    </nav>
  </section>
</header>

templates/icons.html
{% load static %}
<section class="bg-white flex justify-center h-8 items-center gap-8">
  <div class="flex justify-between">
    <span class=""
      ><a target="_blank" href="https://github.com/njeruthuo"
        ><img
          style="height: 22px; margin-right: 10px"
          src="{% static 'img/github.png' %}"
          alt="" /></a
    ></span>
    <span
      ><a
        target="_blank"
        href="https://www.linkedin.com/in/julius-njeru-37158924b/"
        ><img
          style="height: 22px; margin-right: 10px"
          src="{% static 'img/linkedin.png' %}"
          alt="" /></a
    ></span>
    <span
      ><a target="_blank" href="mailto:juliusn411@gmail.com"
        ><img
          style="height: 22px; margin-right: 10px"
          src="{% static 'img/email.png' %}"
          alt="" /></a
    ></span>
  </div>
</section>

templates/introduction.html
{% load static %}

<section
    id="intro"
    class="widescreen:section-min-height tallscreen:section-min-height mb-12 flex scroll-mt-40 flex-col-reverse items-center justify-center gap-8 p-6 sm:flex-row"
  >
    <article class="sm:w-1/2">
      <h2
        class="max-w-md text-center text-4xl font-bold text-slate-900 dark:text-white sm:text-left sm:text-5xl"
      >
        I'm Julius Njeru,
        <span class="text-indigo-700 dark:text-indigo-300"
          >a software developer</span
        >.
      </h2>
      <p
        class="mt-4 max-w-md text-center text-2xl text-slate-700 dark:text-slate-400 sm:text-left"
      >
        I am a passionate and talented young graduate who enjoys the art of
        creating python applications using Django.
      </p>
    </article>
    <img class="w-1/2 flex justify-center align-center rounded" src="{% static 'img/ready.jpg' %} " alt="developer's image" />
  </section>

templates/projects.html
<style>
  .fixed-height-img {
    max-width: 100%;
    height: 200px;
  }
</style>

<section
  id="projects"
  class="widescreen:section-min-height tallscreen:section-min-height my-12 scroll-mt-20 p-6"
>
  <h2
    class="mb-6 text-center text-4xl font-bold text-slate-900 dark:text-white sm:text-5xl"
  >
    My Projects
  </h2>
  <ul
    class="mx-auto my-12 flex list-none flex-col items-center gap-8 sm:flex-row"
  >
    {% for project in projects %}

    <li
      class="flex w-2/3 flex-col items-center rounded-3xl border border-solid border-slate-900 bg-white py-6 px-2 shadow-xl dark:border-gray-100 dark:bg-black sm:w-5/6"
    >
      {% if project.image %}

      <img
        src="{{ project.image.url }}"
        alt="Image"
        class="mb-6 w-1/2 fixed-height-img rounded"
      />
      {% endif %}
      <h3 class="text-center text-xl text-slate-900 dark:text-white">
        {{ project.title }}
      </h3>
      <p
        class="hidden text-center text-sm text-slate-500 dark:text-slate-400 sm:block"
      >
        <a
          href="{{ project.get_absolute_url }}"
          class="btn btn-primary mt-auto"
        >
          Read More
        </a>
      </p>
    </li>
    {% endfor %}
  </ul>
  {% include "includes/pagination.html" with page=projects %}
</section>

templates/testimonials.html
<section
  id="testimonials"
  class="widescreen:section-min-height tallscreen:section-min-height my-12 scroll-mt-20 p-6"
>
  <h2
    class="mb-6 text-center text-4xl font-bold text-slate-900 dark:text-white sm:text-5xl"
  >
    Testimonials
  </h2>
  <figure class="my-12">
    <blockquote
      class="relative rounded-3xl bg-teal-600 py-12 pl-14 pr-8 dark:bg-black"
    >
      <p
        class="mt-2 text-left text-2xl text-white before:absolute before:top-0 before:left-0 before:translate-x-2 before:translate-y-2 before:transform before:font-serif before:text-9xl before:text-white before:opacity-25 before:content-['\201C'] after:absolute after:-bottom-20 after:right-0 after:-translate-x-2 after:-translate-y-2 after:transform after:font-serif after:text-9xl after:text-white after:opacity-25 after:content-['\201D'] dark:text-slate-400 sm:text-3xl"
      >
        Delivers exceptional work within the required timeframe.
      </p>
    </blockquote>
    <figcaption
      class="mt-2 text-right text-xl italic text-slate-500 dark:text-slate-400 sm:text-2xl"
    >
      &#8212;Jeff, Lamwa VetCare.
    </figcaption>
  </figure>
  <figure class="my-12">
    <blockquote
      class="relative rounded-3xl bg-teal-600 py-12 pl-14 pr-8 dark:bg-black"
    >
      <p
        class="mt-2 text-left text-2xl text-white before:absolute before:top-0 before:left-0 before:translate-x-2 before:translate-y-2 before:transform before:font-serif before:text-9xl before:text-white before:opacity-25 before:content-['\201C'] after:absolute after:-bottom-20 after:right-0 after:-translate-x-2 after:-translate-y-2 after:transform after:font-serif after:text-9xl after:text-white after:opacity-25 after:content-['\201D'] dark:text-slate-400 sm:text-3xl"
      >
        Easy to work with. He doesn't need reminders or much supervision.
      </p>
    </blockquote>
    <figcaption
      class="mt-2 text-right text-xl italic text-slate-500 dark:text-slate-400 sm:text-2xl"
    >
      &#8212;Derrick Shiberenje, ShoeSoko.
    </figcaption>
  </figure>
  <figure class="my-12">
    <blockquote
      class="relative rounded-3xl bg-teal-600 py-12 pl-14 pr-8 dark:bg-black"
    >
      <p
        class="mt-2 text-left text-2xl text-white before:absolute before:top-0 before:left-0 before:translate-x-2 before:translate-y-2 before:transform before:font-serif before:text-9xl before:text-white before:opacity-25 before:content-['\201C'] after:absolute after:-bottom-20 after:right-0 after:-translate-x-2 after:-translate-y-2 after:transform after:font-serif after:text-9xl after:text-white after:opacity-25 after:content-['\201D'] dark:text-slate-400 sm:text-3xl"
      >
        A very fast learner. He picked React under my mentorship and he was
        already making simple applications within a week's time!
      </p>
    </blockquote>
    <figcaption
      class="mt-2 text-right text-xl italic text-slate-500 dark:text-slate-400 sm:text-2xl"
    >
      &#8212; Felex Onyango, Sibasi Ltd.
    </figcaption>
  </figure>
</section>